{% set name = "gdsfactory" %}
{% set version = "5.26.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdsfactory-{{ version }}.tar.gz
  sha256: 184d020629cdb52518295d737243f97fa0114762701e02697bfdd39c3b368d7f


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - gf = gdsfactory.gf:gf

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - flatdict
    - gdspy
    - jsondiff
    - loguru
    - matplotlib-base
    - numpy
    - omegaconf
    - orjson
    - pandas
    - phidl ==1.6.2
    - pydantic
    - pytest
    - pytest-regressions
    - python >=3.7
    - pyyaml
    - qrcode
    - rectpack
    - scipy
    - shapely
    - toolz
    - tqdm
    - types-pyyaml
    - typing-extensions
    - watchdog
    - xmltodict

test:
  imports:
    - gdsfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python library to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
