{% set name = "gdsfactory" %}
{% set version = "6.109.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdsfactory-{{ version }}.tar.gz
  sha256: 5c2818803c09e5721ac0f47add5e0e298ba64c296546041dd0293b55899ba8ae


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - gf = gdsfactory.gf:gf

requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - click
    - flatdict
    - gdstk
    - loguru
    - matplotlib-base
    - numpy
    - omegaconf
    - orjson
    - pandas
    - pydantic
    - pytest
    - pytest-regressions
    - python >=3.7
    - pyyaml
    - qrcode
    - rectpack
    - scipy
    - shapely
    - toolz
    - tqdm
    - types-pyyaml
    - typing-extensions
    - watchdog
    - xmltodict
    - rich
    - jinja2

test:
  imports:
    - gdsfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python library to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
