{% set name = "gdsfactory" %}
{% set version = "5.55.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdsfactory-{{ version }}.tar.gz
  sha256: fd0abc5e731f97c8d5522a0cafb257a5598214d1f557b3f73a2292d5e88a2d76


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - gf = gdsfactory.gf:gf

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - flatdict
    - gdspy
    - jsondiff
    - loguru
    - matplotlib-base
    - numpy
    - omegaconf
    - orjson
    - pandas
    - phidl
    - pydantic
    - pytest
    - pytest-regressions
    - python >=3.7
    - pyyaml
    - qrcode
    - rectpack
    - scipy
    - shapely
    - toolz
    - tqdm
    - types-pyyaml
    - typing-extensions
    - watchdog
    - xmltodict
    - lxml

test:
  imports:
    - gdsfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python library to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
