{% set name = "gdsfactory" %}
{% set version = "7.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gdsfactory-{{ version }}.tar.gz
  sha256: 293815952968403e3c3e7f3ceabebe41a9397d0dfc1f1f865006d769cdedde9f


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  entry_points:
    - gf = gdsfactory.gf:gf

requirements:
  host:
    - pip
    - python >=3.7
    - flit
  run:
    - click
    - flatdict
    - gdstk
    - loguru
    - matplotlib-base
    - numpy
    - omegaconf
    - orjson
    - pandas
    - pydantic <2.0
    - pytest
    - pytest-regressions
    - python >=3.7
    - pyyaml
    - qrcode
    - rectpack
    - scipy
    - shapely
    - toolz
    - tqdm
    - types-pyyaml
    - typing-extensions
    - watchdog
    - xmltodict
    - rich
    - jinja2

test:
  imports:
    - gdsfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gdsfactory/gdsfactory
  summary: python library to generate GDS layouts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
